name = "zedtopvibes-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "zedtopvibes-db"
database_id = "73f2a3ac-0d13-454b-9e77-36d5a78c1762"

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "zedtopvibes-audio"